-- Most and least revenue generated by an order.
-- Fix: the original took MAX/MIN over order *lines*. An order's revenue is the sum of its lines.
SELECT MAX(order_revenue) AS max_order_revenue,
       MIN(order_revenue) AS min_order_revenue
FROM (
    SELECT order_id, SUM(revenue) AS order_revenue
    FROM sales
    GROUP BY order_id
) AS orders;
